# Generated by Django 3.0.5 on 2021-02-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0004_auto_20210218_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultmessmenu',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
