# Generated by Django 3.0.5 on 2021-05-12 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0016_auto_20210507_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 12)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('approved', 'Approved'), ('check mail', 'check mail')], default='sent', max_length=10),
        ),
        migrations.AlterField(
            model_name='mealdeadline',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 12)),
        ),
        migrations.AlterField(
            model_name='messattendance',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 12)),
        ),
    ]
