# Generated by Django 3.0.5 on 2021-04-17 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0011_auto_20210415_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultmessmenu',
            name='category',
            field=models.TextField(choices=[('veg', 'veg'), ('egg', 'egg'), ('chicken', 'chicken')], default='veg', max_length=15),
        ),
        migrations.AddField(
            model_name='messmenu',
            name='category',
            field=models.TextField(choices=[('veg', 'veg'), ('egg', 'egg'), ('chicken', 'chicken')], default='veg', max_length=15),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 17)),
        ),
        migrations.AlterField(
            model_name='mealdeadline',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 17)),
        ),
        migrations.AlterField(
            model_name='messattendance',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 17)),
        ),
    ]
