# Generated by Django 3.0.5 on 2021-04-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0012_auto_20210417_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messmenu',
            name='category',
            field=models.TextField(choices=[('veg', 'Vegetarian'), ('egg', 'Has Egg'), ('chicken', 'Has Chicken')], default='veg', max_length=15),
        ),
    ]
