# Generated by Django 3.0.5 on 2021-05-07 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0014_auto_20210505_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultmessmenu',
            name='category',
        ),
        migrations.RemoveField(
            model_name='messmenu',
            name='category',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 7)),
        ),
        migrations.AlterField(
            model_name='mealdeadline',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 7)),
        ),
        migrations.AlterField(
            model_name='messattendance',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 7)),
        ),
    ]
