# Generated by Django 3.0.5 on 2021-05-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0015_auto_20210507_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultmessmenu',
            name='contains_chicken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='defaultmessmenu',
            name='contains_egg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='defaultmessmenu',
            name='special_menu',
            field=models.BooleanField(default=False),
        ),
    ]
