# Generated by Django 3.0.4 on 2020-03-29 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0002_auto_20200329_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='type',
            new_name='userType',
        ),
    ]
