# Generated by Django 3.0.4 on 2020-03-29 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0003_auto_20200329_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userType',
        ),
    ]
