# Generated by Django 3.0.5 on 2021-02-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0005_auto_20210218_1345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultMessMenu',
        ),
    ]
