# Generated by Django 3.0.4 on 2020-04-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0006_menuitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitems',
            name='quantity',
        ),
    ]
