# Generated by Django 3.0.4 on 2020-04-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0007_remove_menuitems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
