# Generated by Django 3.0.5 on 2021-02-25 18:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0007_defaultmessmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.date(2021, 2, 25)),
        ),
        migrations.AlterField(
            model_name='mealdeadline',
            name='date',
            field=models.DateField(default=datetime.date(2021, 2, 25)),
        ),
        migrations.AlterField(
            model_name='messattendance',
            name='date',
            field=models.DateField(default=datetime.date(2021, 2, 25)),
        ),
        migrations.CreateModel(
            name='AppFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(max_length=500)),
                ('timestamp', models.DateTimeField()),
                ('status', models.CharField(choices=[('Sent', 'Sent'), ('Resolved', 'Resolved')], default='Sent', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_app_feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
