# Generated by Django 3.0.5 on 2021-02-25 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0008_auto_20210225_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appfeedback',
            old_name='response',
            new_name='feedback',
        ),
    ]
