# Generated by Django 3.0.4 on 2020-05-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0010_auto_20200502_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='orderPlaced',
            field=models.BooleanField(default=False),
        ),
    ]
