# Generated by Django 3.0.5 on 2021-04-15 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0010_auto_20210402_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='messmenu',
            name='occasion',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 15)),
        ),
        migrations.AlterField(
            model_name='mealdeadline',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 15)),
        ),
        migrations.AlterField(
            model_name='messattendance',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 15)),
        ),
    ]
