# Generated by Django 3.0.4 on 2020-05-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0012_auto_20200505_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='orderPlaced',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=0),
        ),
    ]
