# Generated by Django 3.0.4 on 2020-05-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0013_auto_20200505_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='orderTime',
            field=models.DateTimeField(default=None),
        ),
    ]
