# Generated by Django 3.0.4 on 2020-05-19 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0014_cart_ordertime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='orderTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
