# Generated by Django 3.1.2 on 2020-11-11 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0015_auto_20200519_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userType',
            new_name='type',
        ),
    ]
