# Generated by Django 3.1.2 on 2020-11-11 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0016_auto_20201111_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='authenticated',
        ),
    ]
