# Generated by Django 3.1.2 on 2020-12-01 08:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0017_remove_user_authenticated'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast_coupons', models.PositiveSmallIntegerField(default=20)),
                ('lunch_coupons', models.PositiveSmallIntegerField(default=20)),
                ('snacks_coupons', models.PositiveSmallIntegerField(default=20)),
                ('dinner_coupons', models.PositiveSmallIntegerField(default=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Snacks', 'Snacks'), ('Dinner', 'Dinner')], max_length=10)),
                ('attending', models.BooleanField(default=True)),
                ('date', models.DateField(default=datetime.datetime(2020, 12, 1, 8, 49, 46, 399344))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mess_customer', to='UserLogin.messuser')),
            ],
        ),
    ]
