# Generated by Django 3.1.2 on 2020-12-01 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0018_messattendance_messuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='messattendance',
            name='editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='messattendance',
            name='date',
            field=models.DateField(default=datetime.date(2020, 12, 1)),
        ),
    ]
