# Generated by Django 3.1.2 on 2020-12-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0021_auto_20201217_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('approved', 'Approved'), ('check mail', 'check mail'), ('rejected', 'Rejected')], default='sent', max_length=10),
        ),
        migrations.AddField(
            model_name='messattendance',
            name='defaulter_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
