# Generated by Django 3.1.2 on 2020-12-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0022_auto_20201217_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messattendance',
            name='defaulter_count',
        ),
        migrations.AddField(
            model_name='messattendance',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messattendance',
            name='defaulter',
            field=models.BooleanField(default=False),
        ),
    ]
