# Generated by Django 3.1.2 on 2020-12-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0023_auto_20201217_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='messattendance',
            name='editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('approved', 'Approved'), ('check mail', 'check mail'), ('penalised', 'Penalised')], default='sent', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('admin', 'Admin'), ('mess-vendor', 'Mess Vendor')], default='customer', max_length=20),
        ),
    ]
